version: 0.1
log:
  accesslog:
    disabled: false
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
loglevel: debug # deprecated: use "log"
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: false
  redirect:
    disable: false
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: 0.0.0.0:5000
  host: https://registry.hengdingsheng.com
  secret: asecretforlocaldevelopment
  relativeurls: false
  debug:
    addr: localhost:5001
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false

notifications:
  endpoints:
    - name: listener
      disabled: false
      url: https://demo.hengdingsheng.com/registry/notifications
      timeout: 3000ms
      threshold: 2
      backoff: 1s
      ignoredmediatypes:
        - application/octet-stream
auth:
  token:
    realm: https://demo.hengdingsheng.com/registry/token
    service: registry
    issuer: red
    rootcertbundle: /certs/domain.crt
